### ISSUE TITLE
add ng-text

### ISSUE THREAD

**Issue by bkuberek** [omichelsen/angular-clipboard#10]
It would be nice to support a `ng-text` that can contain model variables such as

```
<a class="btn btn-default" clipboard ng-text="some-command --createuser --firstname '{{person.first_name}}' --lastname '{{person.last_name}}' -u '{{person.username}}' -a -g '{{person.groups | join:','}}'"><i class="fa fa-files-o"></i> Copy</a>
```

**Comment by populationtwo** [comment]
+1

@omichelsen How can I help? I'd be happy to create a PR if someone can give me an insight how to achieve this.

**Comment by omichelsen** [comment]
I'm not really familiar with the syntax you are describing, but if I understand you correctly, you would like to run a command that returns/changes the value that should be copied?

You can achieve this by using `ng-click` on the link/button like this:

```html
<button clipboard ng-text="myTextVar'" ng-click="changeText()">Copy</button>
```
and then this in the controller:
```js
$scope.myTextVar = 'initial value';
$scope.changeText = function () {
    $scope.myTextVar = 'some other value';
};
```
