### ISSUE TITLE
Didn't work on Firefox

### ISSUE THREAD

**Issue by nguyennb9** [omichelsen/angular-clipboard#11]
I tried your demo (https://rawgit.com/omichelsen/angular-clipboard/master/demo/demo.html) and got an error:

Error! Object { result=2147500037,  name="NS_ERROR_FAILURE",  filename="https://rawgit.com/omich...er/angular-clipboard.js",  more...}
demo.html (line 29)

Firefox version 38.0
Linux mint 17.1

**Comment by NarmadhaThiru** [comment]
Not working in Firefox. Same error
Error!  Object { result=2147500037,  name="NS_ERROR_FAILURE",  filename="http://localhost:3002/bo...rd/angular-clipboard.js",  more...}

**Comment by omichelsen** [comment]
@NarmadhaThiru only Firefox 41+ is supported.
