### ISSUE TITLE
Can we have a service that could handle the copy to clipboard feature without having to click on a button?

### ISSUE THREAD

**Issue by dejavu1987** [omichelsen/angular-clipboard#16]
Hi,
Thanks for the module. Will it be possible to have a service that can be injected and used for  a copy to clipboard functionality? I have a use case where I can not show the copy to the clipboard button but some other generic link has to do this action dynamically.
thanks and regards

**Comment by omichelsen** [comment]
You don't need to use the directive with a button, it can also be applied to links, divs etc.

**Comment by dejavu1987** [comment]
Yes.. but I can have access to dom because the api only lets me add a callback action to my links so I wanted to use the functionality just inside a callback function without having to do anything with dom.
Example:

actionLabel: 'Copy text',
actionCallback: function(text){
// call some service methods to copy text to the clipboard
clipboardService.copyText(text);
}

**Comment by omichelsen** [comment]
Makes sense, I've published a new version exposing a `clipboard` service, which you can use as suggested.

**Comment by dejavu1987** [comment]
Thanks @omichelsen
