### ISSUE TITLE
Nothing is copied in Chrome Canary when CSS styles of body has '-webkit-user-select:none'

### ISSUE THREAD

**Issue by ziliwesley** [omichelsen/angular-clipboard#2]
version of Chrome Canary:  45.0.2434.0 canary (64-bit).

And my workaround is temporarily change the `document.body.style.webkitUserSelect` to `initial` to override styles in CSS files and reset it after the selection is successfully done.

And I have made a pr request, hope that will help.

**Comment by omichelsen** [comment]
Thanks for the PR, but I can't recreate this problem in [the demo](https://rawgit.com/omichelsen/angular-clipboard/master/demo/demo.html) current Chrome (44) or current Canary (46)?

**Comment by ziliwesley** [comment]
The demo itself works fine in either version of Chrome.
It fails only if a css style of "-webkit-user-select:none" is present
