### ISSUE TITLE
Don't require angular in module.exports

### ISSUE THREAD

**Issue by BartCorremans** [omichelsen/angular-clipboard#22]
Adding angular as a peerDependency in package.json and requiring it in `module.exports` causes issues when an app loads angular through a CDN instead of as an npm package:

> Error: Cannot find module 'angular'

Most angular plugins assume angular is already defined and don't make any `require()` calls themselves.

**Comment by omichelsen** [comment]
Just to clarify, are you running this in a site that uses RequireJS, or are you not using any module bundlers at all?

**Comment by BartCorremans** [comment]
I should've clarified, sorry. We're using npm with browserify to bundle most of our dependencies, but some of the larger ones like angular itself are loaded via a CDN instead. 

The problem then arises when angular plugins attempt to require() angular and list it as a dependency (or peerDependency). 

It's probably safe to assume that angular will already be loaded by the time this module is loaded, be it through a CDN or through `require('angular')` earlier in the site's bootstrap.

**Comment by omichelsen** [comment]
I can of course change the source, but the UMD pattern is pretty standard, and you will probably have problems with other packages as well.

How about [this solution](http://stackoverflow.com/a/21800208/595844), to fix the require statement?

**Comment by BartCorremans** [comment]
Unfortunately I cannot put together a working configuration where browserify-shim will correctly resolve the `require('angular')` call in angular-clipboard.js (similar to neurosnap's comment in the discussion you linked).

**Comment by Oceanswave** [comment]
+1

When angular-clipboard is used in conjunction with webpack, it throws the error on OP's comment as well.

**Comment by Oceanswave** [comment]
This is the pattern used in angular-file-upload:

https://github.com/nervgh/angular-file-upload/blob/master/dist/angular-file-upload.js

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["angular-file-upload"] = factory();
	else
		root["angular-file-upload"] = factory();
})(this, function() { ... }
```

doesn't seem to reference 'angular', but it works great.

**Comment by omichelsen** [comment]
It works because they are actually not using angular as a dependency but just expecting it to be a global variable. That is not the point of UMD/AMD.

**Comment by Oceanswave** [comment]
Agree. I switched my webpack requires to using node dependencies rather than bower hosted dependencies and that worked a lot better.

Thanks.
