### ISSUE TITLE
Add a directive to automatically hide an element if copy isn't supported

### ISSUE THREAD

**Issue by niemyjski** [omichelsen/angular-clipboard#24]
[ng-clip](https://github.com/asafdav/ng-clip) has an attribute called auto-hide-on-no-flash that hides an element it's placed on if copying isn't supported. Is there any chance we could add something like this? I might want to add progressive enhancements when copy is supported.

**Comment by niemyjski** [comment]
This is really the only thing preventing me from moving over. I know this is something I could do myself... but it would be nice to just have it built in.

**Comment by niemyjski** [comment]
Looks like we could check for the existence of `Document.queryCommandSupported()` as well as calling that and pass it `copy` could control this directive!

**Comment by niemyjski** [comment]
If you want I could do a pull request for this. I made a directive in my own project that checks this compatibility. Would be nice if the service exposed this check as well.

**Comment by omichelsen** [comment]
I would really like to include support for a "supported" indicator, but it is notoriously difficult to detect.

Unfortunately `Document.queryCommandSupported('copy')` isn't a reliable method to check for this since e.g. Safari doesn't support this command, even in the latest preview version where it _does_ support copy+paste.

Only thing I have found is dumb browser detection which I would prefer to avoid.

**Comment by niemyjski** [comment]
I can confirm that it supports it as I tested safari 9.1, firefox and chrome latest on osx yesterday. They all returned the correct results (true/false) and didn't throw an exception.

**Comment by niemyjski** [comment]
But I saw we have a service which checks this and if the function doesn't exist, returns false or throws an error then we say it's not supported and don't fall back to dumb browser detection. It's better to say it's not supported then assume it is.

**Comment by omichelsen** [comment]
Thanks for checking into this. Do you have an overview whether support for `queryCommandSupported` (and the response) === supported? 

So far I have the correct response for all current browsers (Safari 9.1 unsupported, Safari 9.1.1 supported etc.), but I would like to ensure that this is reliable across all the browsers?

**Comment by omichelsen** [comment]
I have created [PR#26](https://github.com/omichelsen/angular-clipboard/pull/26) to implement this feature. With that you can do `supported="supported" ng-show="supported"` on the directive to hide it if the feature detection comes back negative.

**Comment by niemyjski** [comment]
It should be reliable as its a spec. I'd recommend try catching it just to be safe. Any reason we should expose a supported directive unless it's two way and updates a users flag? I think having it on clipboard service is enough. Can we also add a helper directive to hide the element when it's not supported

**Comment by omichelsen** [comment]
I would prefer that people use `ng-show`/`ng-hide` or whatever hiding logic they prefer. Not everybody prefer to hide with css `display: none`, so we shouldn't mix that into this directive.

**Comment by niemyjski** [comment]
@omichelsen I see that you added supported="supported" and you set the scope supported in the link to clipboard.supported ... But then your demos also define supported... I tried to see if I could just do something like this

<button clipboard text="sample" supported="$ctrl.supported" ng-if="$ctrl.supported"/> with no other code in my controller and it doesn't seem that the two way binding + link code picks this up. It's been a long day and I could be missing something but it kinda sucks if I have to inject the clipboard service to set this in a second place when the two way binding should handle it.

**Comment by niemyjski** [comment]
Doh, just noticed why it failed (I'm an idiot). I do ng-if almost 100% of the time and so the default will be false cause the variable is not defined so the rest of the directives won't run and thus update the value. Changing to ng-show fixed the issue.

**Comment by niemyjski** [comment]
@omichelsen worth a read on why I chose ng-if: http://angularjs.blogspot.com/2016/04/5-rookie-mistakes-to-avoid-with-angular.html
