### ISSUE TITLE
Multi-line Copy

### ISSUE THREAD

**Issue by asontha** [omichelsen/angular-clipboard#3]
Hello, 

I recently used the directive in my own project and it was great but one problem was multi-line copying. I tried using line breaks and even carriage returns but they both eventually broke. I finally got around it by changing node.textContent to node.innerHTML within the createNode function. Then all I had to do was put line break tags in my txt and now it formats perfectly to new lines and the copying also keeps the formatting. 

Just wondering if you'd like the update for multi-line copying.

**Comment by omichelsen** [comment]
Thanks for the heads up.

I've chosen `textContent` as a matter of best practice to avoid an XSS attack vector, but I can see the advantage for enabling coping of HTML as well.

I will consider whether to change it completely to `innerHTML` or maybe make it optional through a property.

**Comment by omichelsen** [comment]
This has now been added with PR #5
