### ISSUE TITLE
Add the ajax response to clipboard using clipboard.copyText(response.content). 

### ISSUE THREAD

**Issue by pvagare** [omichelsen/angular-clipboard#30]
Example:

Add the below code on the ng-click. 

   $http.get($scope.selectedRow.Id).then(function (result) {
           clipboard.copyText(response.content).
    });

on executing ng-click. I am getting the failure exception.
Please let us know How to use clipboard.copyText in above case.

**Comment by omichelsen** [comment]
For security reasons you can only modify the user clipboard as a result of a user action (click). 

Doing a ajax request is an async operation, and thus you are no longer in the context of the click action, and the browser won't let you add to clipboard.

**Comment by benbieler** [comment]
@omichelsen, @pvagare code from a work related project, where we had a similar issue:

```javascript
var request = new XMLHttpRequest();
                request.open('GET', '/api/items/' + encodeURIComponent(item.shortId) + '/value', false);  // `false` makes the request synchronous
                request.send(null);
                if (request.status === 200) {
                    console.log(request.responseText);
                    clipboard.copyText(request.responseText);
                } else {
                    toastr.error('Error copying the value (XHR)', 'Error');
                }
```


Hope this could help anybody encountering a similar issue...

**Comment by sg6** [comment]
@benbieler saved my day! Works like a charm, thanks!

**Comment by benbieler** [comment]
Sure. No Problem ;) @sg6

**Comment by gitnik** [comment]
FYI this is no longer advisable since synchronous request are being deprecated and should therefore not be used https://xhr.spec.whatwg.org/#synchronous-flag

**Comment by ThomasHambach** [comment]
A workaround is using a setInterval to check whether your async call has finished. Disclaimer, I would not recommend this unless you have to make it work.

            let data = await yourAsyncFunction();

            let interval = window.setInterval(() => {
                if (data) {
                    clearInterval(interval);
                    this.clipboard.copyText(data);
                }
            }, 100);
