### ISSUE TITLE
IE: Prevent page scrolling on copy

### ISSUE THREAD

**Issue by kremerd** [omichelsen/angular-clipboard#33]
On larger pages the scrollbar will jump to the hidden node, i.e. the end of the document on node.select() - at least in IE 11. You can try it at https://plnkr.co/JMOnatFAlWrh0R53FuTu.

**Comment by kremerd** [comment]
I see two options to adress this problem:

1. Insert the node into the element that was clicked rather than the end of the document, and hide it properly.

2. Capture the scrollbar position and reset it if neccessary (as done in my PR).

**Comment by omichelsen** [comment]
I have just released [v1.4.2](https://github.com/omichelsen/angular-clipboard/commit/981356082f5983fd594f4afd61d90423099976cb) with a fix for this.

**Comment by kremerd** [comment]
Thanks for the update. I just tested the new version and indeed it improves the situation. However it's not perfect yet: Sometimes the browser jumps to some point above the triggering button. You can try it out yourself at a slightly modified Plunkr: https://embed.plnkr.co/c96NT4uANM33BW55NCjw/
