### ISSUE TITLE
Typescript definitions file

### ISSUE THREAD

**Issue by Dretch** [omichelsen/angular-clipboard#40]
It would be nice to have a Typescript file for `angular-clipboard` in https://github.com/DefinitelyTyped/DefinitelyTyped/.

I can probably do this if you are not interested.

**Comment by omichelsen** [comment]
There's not much of an API and I don't personally use TypeScript, so feel free to submit something if you like 👍

**Comment by bradfordwagner** [comment]
@omichelsen I made a successful [pull](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12458) request into DefinitelyTyped for angular-clipboard.

**Comment by omichelsen** [comment]
Very nice, thanks!
