### ISSUE TITLE
Cannot copy url

### ISSUE THREAD

**Issue by ArtworkAD** [omichelsen/angular-clipboard#49]
` angular.js:13920Error: [$parse:syntax] Syntax Error: Token ':' is an unexpected token at column 5 of the expression [http://...] starting at [://...].
`

when

    text="http://..."

So when text contains a url angular-clipboard is failing with the above error message.

**Comment by omichelsen** [comment]
The `text` attribute takes a variable and not a string, so you should put your url in a variable like `$scope.myUrl = 'http://...';` and bind it with `text="myUrl"`.

For reference, the difference in scope bindings is explained here: http://stackoverflow.com/a/28310787/595844
