### ISSUE TITLE
 it doesn't retain the format. it turns to a single line. I'd like to retain the json format when copy to somewhere else.

### ISSUE THREAD

**Issue by phanthinh** [omichelsen/angular-clipboard#53]
Hi everybody

it doesn't retain the format. it turns to a single line. I'd like to retain the json format when copy to somewhere else.

![untitled_2_and_untitled](https://cloud.githubusercontent.com/assets/5910795/19190697/3130700e-8cc9-11e6-8164-138163093b54.png)

**Comment by fredrikw** [comment]
Hello,

Most likely you JSON is a single line, at least I have had no problems copying multiline comments so my guess is that you JSON string actually looks like that and that if you would like to have it "prettyprinted" you need to take car of that before calling copyText

**Comment by phanthinh** [comment]
My mistake.
