### ISSUE TITLE
On ios clicking the copy button does not copy

### ISSUE THREAD

**Issue by iwarner** [omichelsen/angular-clipboard#54]
When testing your demo in iOS it just brings up the keyboard and does not copy

**Comment by phishy** [comment]
iOS doesn't support execCommand copy, that's why. https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by iwarner** [comment]
Thanks

I based my assumption on this : http://caniuse.com/#search=execCommand

**Comment by phishy** [comment]
Apple has a tendency to be.. um... forceful. They want the user to do their own copying. *sigh*

**Comment by Blackbaud-MatthewBell** [comment]
I understand that iOS doe not seem to support the clipboard.  That said, the "supported" check seems to come back as true for iOS.  Could the supported logic be improved to make it easier to degrade for iOS?

**Comment by omichelsen** [comment]
Our only option is to do an old-school user agent check, but then if iOS finally adds support, the library won't work.

**Comment by shrpne** [comment]
Here is a solution: https://stackoverflow.com/a/41267511
Can it be implemented?
