### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by jlebit** [omichelsen/angular-clipboard#6]
I've just tested the demo on IE11 and it does not seem to work. The content is not copied to the clipboard even if the logs show "Copied!".
The version of my browser is Internet Explorer 11.0.9600.17959

**Comment by omichelsen** [comment]
You should get a security prompt asking you if you will allow for the content to be placed in your clipboard. If you don't see this prompt you might be running with increased/custom security levels (from a domain policy maybe).

**Comment by jlebit** [comment]
I cannot check these security settings (I don't have the permissions), so you are probably right.
