### ISSUE TITLE
Throw error: "failure copy"

### ISSUE THREAD

**Issue by ibbatta** [omichelsen/angular-clipboard#63]
When I try to copy a result from a promise it throw an error in console `failure copy`
I use angular 1.5.8

The browser I use is full supported as the documentation provided

**Comment by PunkHaz4rd** [comment]
+1

**Comment by Picazamora** [comment]
+2

**Comment by Picazamora** [comment]
Relation with #65 and solution #30

**Comment by gitnik** [comment]
FYI this is no longer advisable since synchronous request are being deprecated and should therefore not be used https://xhr.spec.whatwg.org/#synchronous-flag
