### ISSUE TITLE
Can't copy data from HTTP call

### ISSUE THREAD

**Issue by Fossil01** [omichelsen/angular-clipboard#65]
This doesn't work:
```javascript
	$scope.copyPassword = function(item) {
		$http.get(API + "/password/" + item.id).then(function(resp) {
			clipboard.copyText('Test');
		}).catch(function(error) {
			console.log(error);
		});
	}
```

But when you move the clipboard.copyTest out of the HTTP call it works:

```javascript
	$scope.copyPassword = function(item) {
		clipboard.copyText('Test');
		$http.get(API + "/password/" + item.id).then(function(resp) {
		}).catch(function(error) {
			console.log(error);
		});
	}
```

Any idea why @omichelsen?

**Comment by omichelsen** [comment]
Copy needs to happen as part of a user initiated action (like `click`). When you move it to an async response, it loses that context and you don't get access to the clipboard.

**Comment by Fossil01** [comment]
Okay so you cannot do what I intended at all?

**Comment by omichelsen** [comment]
You might be able to accomplish it using the workaround from https://github.com/omichelsen/angular-clipboard/issues/30.
