### ISSUE TITLE
How do i feature detect if SelectionAPI or ClipboardAPI is supported by my browser without user interaction and hide the copy button if not available ?

### ISSUE THREAD

**Issue by siva-I** [omichelsen/angular-clipboard#7]
How do i feature detect if SelectionAPI or ClipboardAPI is supported by my browser without user interaction and hide the copy button if not available ?
Basically i want to disable the Copy button if the browser is old and doesn't support this feature.

Please advise

**Comment by omichelsen** [comment]
Unfortunately it seems that this is almost impossible to detect without some user interaction:
https://github.com/zeroclipboard/zeroclipboard/issues/171
https://developers.google.com/web/updates/2015/04/cut-and-copy-commands

**Comment by arve0** [comment]
As a fallback, you may use `navigator.userAgent` up front to test that you have either Chrome 43+, Firefox 41+, Opera 29+ or IE10+.

**Comment by fracz** [comment]
The directive could implement this OOTB so we would not have to repeat the code in every project. E.g.

```
<button clipboard text="textToCopy" hide-if-not-supported="true">Copy</button>
```

**Comment by omichelsen** [comment]
[PR#26](https://github.com/omichelsen/blog-social-signin-spa-jwt-server/issues/1) might help you, with this you can do `supported="supported" ng-show="supported"`.
