### ISSUE TITLE
Should the title function be bound with & instead of =?

### ISSUE THREAD

**Issue by scrussell24** [omichelsen/angular-clipboard#9]
I was able to integrate this into a project but I had to update to bind the text callback with & instead of = and evaluate the expression when clicked (ie. scope.$eval(scope.text)). Any chance this can be changed? I can send a pull-request. Or perhaps this can be added as a separate attribute. 

Thanks!

Scott

**Comment by omichelsen** [comment]
Hey, `text` is supposed to be a reference to a variable, so that it can be updated dynamically.

By changing it to `&` you have to do `eval` to achieve the same thing.

Have you had problems updating the text value?
